site_name: BaGet
site_description: A lightweight NuGet service implementation
site_author: Loic Sharma
site_url: https://loic-sharma.github.io/BaGet/

repo_name: loic-sharma/BaGet
repo_url: https://github.com/loic-sharma/BaGet

copyright: 'Copyright &copy; 2018 Loic Sharma'

theme:
  name: material
  language: en
  palette:
    primary: yellow
    accent: yellow
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - type: github-alt
      link: https://github.com/loic-sharma
    - type: twitter
      link: https://twitter.com/sharmaloic

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true

pages:
  - Overview: index.md
  - Getting Started:
    - On your computer: quickstart/local.md
    - Docker: quickstart/docker.md
    - Azure: quickstart/azure.md
    - AWS: quickstart/aws.md
    - Google Cloud: quickstart/gcp.md
    - Windows IIS Proxy: quickstart/iis-proxy.md
  - Configuration: configuration.md
  - Tools:
    - Mirroring: tools/mirroring.md
  - BaGet vs. Other:
    - nuget.org: vs/nugetorg.md
    - NuGet.Server: vs/nugetserver.md
    - Azure Artifacts: vs/azure-artifacts.md
    - MyGet: vs/myget.md
    - LiGet: vs/liget.md
    - Artifactory: vs/artifactory.md
    - Nexus: vs/nexus.md
    - TeamCity: vs/teamcity.md