site_name: BaGet
site_description: A lightweight NuGet and symbol server
site_author: Loic Sharma
site_url: https://loic-sharma.github.io/BaGet/

repo_name: loic-sharma/BaGet
repo_url: https://github.com/loic-sharma/BaGet

copyright: 'Copyright &copy; 2020 Loic Sharma'

theme:
  name: material
  language: en
  palette:
    primary: yellow
    accent: yellow
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - type: github-alt
      link: https://github.com/loic-sharma
    - type: twitter
      link: https://twitter.com/bagetapp

markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true

pages:
  - Overview: index.md
  - Installation:
    - On your computer: installation/local.md
    - Docker: installation/docker.md
    - Azure: installation/azure.md
    - AWS: installation/aws.md
    - Google cloud: installation/gcp.md
    - Alibaba cloud: installation/aliyun.md
    - Windows IIS proxy: installation/iis-proxy.md
  - Configuration: configuration.md
  - Import:
    - Local feeds: import/local-feeds.md
    - NuGet.Server: import/nugetserver.md
    - NuGet.org: import/nugetorg.md
  - Advanced:
    - Debugging: advanced/debugging.md
    - BaGet SDK: advanced/sdk.md
  - BaGet vs. other:
    - nuget.org: vs/nugetorg.md
    - NuGet.Server: vs/nugetserver.md
    - Local feeds: vs/local-feeds.md
    - Azure Artifacts: vs/azure-artifacts.md
    - MyGet: vs/myget.md
    - LiGet: vs/liget.md
    - Artifactory: vs/artifactory.md
    - Nexus: vs/nexus.md
    - TeamCity: vs/teamcity.md
